config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: { sessions: "admins/sessions"}
  resources :pages
  root 'weeks#current'
  namespace :api do
    namespace :vi do
      resources :memory_verses
    end
  end
  resources :seasons
  resources :reading_lists
  resources :creative_responses
  resources :memory_verses
  resources :weeks do
    resources :memory_verses
    resources :mealtime_prayers
    resources :creative_responses
    resources :service_ideas
    resources :faith5s
    resources :shares
    resources :talks
    resources :prays
    resources :blesses
    resources :reading_lists do
      :days
    end
    member do
      get :user_view
    end
    member do
      get :mobile_view

    end
    collection do 
      get :current_week
      get :current
    end
    member do
      get :manage_weeks_current
    end
    member do
      post :add_to_queue
    end
    member do
      post :remove_from_queue
    end
    member do
      post :mark_complete
    end
    member do
      post :publish
    end
    collection do
      get :queue
    end
    member do
      get :manage_weeks_queue
    end
    collection do
      get :archives
    end
    member do
      get :manage_weeks_archived
    end
    member do
      get :user_view_archived
      get :user_view_current
      get :user_view_queue
      get :user_view_new
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/bless.rb
class Bless < ApplicationRecord
  belongs_to :week
end

app/models/day.rb
class Day < ApplicationRecord
  belongs_to :reading_list
end

app/models/faith5.rb
class Faith5 < ApplicationRecord
  belongs_to :week
end

app/models/memory_verse.rb
class MemoryVerse < ApplicationRecord
  belongs_to :week
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/pray.rb
class Pray < ApplicationRecord
  belongs_to :week
end

app/models/reading_list.rb
class ReadingList < ApplicationRecord
  belongs_to :week
  has_many :days
end

app/models/season.rb
class Season < ApplicationRecord
  has_many :weeks
end

app/models/service_idea.rb
class ServiceIdea < ApplicationRecord
  belongs_to :week
end

app/models/share.rb
class Share < ApplicationRecord
  belongs_to :week
end

app/models/talk.rb
class Talk < ApplicationRecord
  belongs_to :week
end

app/models/week.rb
class Week < ApplicationRecord
  has_many :reading_lists 
  has_many :faith5s
  has_many :service_ideas
  has_many :creative_responses
  has_many :mealtime_prayers
  has_many :memory_verses
  has_many :shares
  has_many :talks
  has_many :prays
  has_many :blesses
  belongs_to :season
  scope :current, -> { 
    where("(published_on < ?) AND 
           (archived_on > ?)", 
            Time.now, Time.now)
  }
  scope :archived, -> { where("archived_on <?", Time.now)}
  scope :queue, -> { where("published_on >?", Time.now)}


end

app/controllers/weeks_controller.rb
class WeeksController < ApplicationController
  before_action :authenticate_admin!, except: [:current, :mobile_view]
  layout "admin", except: [:current, :mobile_view]
  def index
  	@weeks = Week.all
  end
  
  def show
    @week = Week.find(params[:id])
    @seasons = Season.all
  end

  def new
  	@week = Week.new
    @weeks = Week.where("queued IS FALSE").order('published_on ASC')
    @seasons = Season.all
  end

  def edit
    @week = Week.find(params[:id])
    @seasons = Season.all
  end

  def create
    @week = Week.new(week_params)
    @seasons = Season.all
    
    if @week.save
      redirect_to @week
    else
	  render 'new'
	end
  end

  def update
    @week = Week.find(params[:id])
    @seasons = Season.all
    if @week.update(week_params)
    	redirect_to @week
    else
      render 'edit'
    end
  end

  def destroy
  	@week = Week.find(params[:id])
  	@week.destroy

  	redirect_to new_week_path
  end

  def user_view
    @week = Week.find(params[:id])
  end

  def mobile_view
    @week = Week.find(params[:id])
    @seasons = Season.all
  end

  def current_week
    @weeks = Week
      .current
      .where("queued IS TRUE")
    @seasons = Season.all
  end

  def current
    week = Week
      .current
      .where("queued IS TRUE")
      .order('published_on ASC, id ASC')
      .first
    if week
      redirect_to mobile_view_week_path(week)
    else
      render :current
    end  
    @seasons = Season.all
  end

  def manage_weeks_current
    @week = Week.find(params[:id])
    @seasons = Season.all
  end

  def queue
    @weeks = Week
      .queue
      .where("queued IS TRUE")
      .order('published_on ASC, id ASC')
    @seasons = Season.all
  end

  def manage_weeks_queue
    @week = Week.find(params[:id])
    @seasons = Season.all
  end

  def archives
    @weeks = Week.archived.where("queued IS TRUE").order('published_on DESC')
    @seasons = Season.all
  end

  def manage_weeks_archived
    @week = Week.find(params[:id])
    @seasons = Season.all
  end

  def user_view_archived
    @week = Week.find(params[:id])
    @seasons = Season.all
  end

  def mark_complete
    @week = Week.find(params[:id])
    @seasons = Season.all

    if @week.update(completed: true)
      flash[:notice] = "#{@week.name} has been marked complete. You can now add the week to the queue. You can still edit the week via Manage Weeks."
      redirect_to new_week_path
    else
      flash[:alert] = "There was an error marking this week complete. Please try again."
    end
  end
  
  def add_to_queue
    @week = Week.find(params[:id])
    @seasons = Season.all

    if @week.update(queued: true)
      flash[:notice] = "#{@week.name} was successfully added to the queue! Manage and view the week through the 'Queued Weeks' tab."
      redirect_to new_week_path
    else
      flash[:alert] = "There was an error adding this week to the queue. Please try again." 
    end

  end
  
  def remove_from_queue
    @week = Week.find(params[:id])
    @seasons = Season.all

    if @week.update(queued: false)
      flash[:notice] = "#{@week.name} was successfully removed from the queue! Manage and view the week in New Weeks."
      redirect_to queue_weeks_path
    else
      flash[:alert] = "There was an error removing this week to the queue. Please try again." 
    end
  end
  #def publish
   # @week = Week.find(params[:id])
    
    #if @week.update(published: true)
     # flash[:notice] = "#{@week.name} was successfully added to current week!"
      #redirect_to current_week_weeks_path
    #else
     # flash[:alert] = "There was an error adding this week to current week. Please try again."
    #end 
  #end

  private
    def week_params
    	params.require(:week).permit(:name, :published_on, :archived_on, :season_id)
    end

end

app/helpers/blesses_helper.rb
module BlessesHelper
end

app/helpers/days_helper.rb
module DaysHelper
end

app/helpers/faith5s_helper.rb
module Faith5sHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/prays_helper.rb
module PraysHelper
end

app/helpers/seasons_helper.rb
module SeasonsHelper
end

app/helpers/shares_helper.rb
module SharesHelper
end

app/helpers/talks_helper.rb
module TalksHelper
end

app/helpers/week_helper.rb
module WeekHelper
end

app/views/weeks/current_week.html.erb
<div class="new-weeks-container">
  <div class="d-flex justify-content-center">
    <h1>Current Week</h1>
  </div>
  <br>
  
  <div class="d-flex justify-content-center">
    <div class="container" style="width: 50%; text-align: center;">
    <p>This is the week that is currently published for users to view.</p>
    </div>
  </div>
  <div class="container-fluid" style="width: 75%;" >
    <table class="table table-striped table-responsive" style="background-color: white;">
      <tr>
        <th>Week Name</th>
        <th>Publishing Dates</th>
        <th></th>
        <th></th>
        <th></th>
      </tr>
      <% @weeks.each do |week| %>
      <tr>
      <td><%= week.name %></td>
      <td><%= week.published_on.strftime("%e %B") %> - <%= week.archived_on.strftime("%e %B, %Y") %></td>
      <td><%= link_to 'Manage Week', manage_weeks_current_week_path(week) %></td>
        <td><%= link_to 'User View', mobile_view_week_path(week), target: "_blank" %></td>
        <td><%= button_to 'Remove from Queue', remove_from_queue_week_path(week), class: "btn btn-danger" %></td>
      </tr>
      <% end %>
    </table>
    <br>
  </div>
</div>

app/views/weeks/manage_weeks_archived.html.erb
<div class="container-fluid">
  <%= link_to 'Back to Archived Weeks', archives_weeks_path %> 
  <br>
  <br>
  <div class="container-fluid">
    <h2><%= @week.name %></h2>
    <p>This week is currently stored in Archived Weeks.</p>
  </div>
  <div class="container-fluid">
    <div class="card">
      <div class="card-block">
        <div class="row">
          <div class="col-sm-12">
            <div class="container">Church Season: <%= @week.season.church_season %></div>
            <div class="container">Publish Date: <%= @week.published_on.strftime("%A, %e %B, %Y")  %></div>
            <div class="container">Archive Date: <%= @week.archived_on.strftime("%A, %e %B, %Y")  %></div>
            <div class="container"><%= link_to 'Edit', edit_week_path(@week) %></div>
          </div>
        </div>
      </div>
    </div>
    <br>
      <div class="card">
        <div class="card-block">
          <br>
          <div class="row">
          <div class="col-sm-6">
            <div class="container">
            <table class="table table-striped table-responsive">
              <thead>Reading List</thead>
              <tr>
                <th>Date</th>
                <th>Verse</th>
                <th>Title</th>
                <th></th>
              </tr>
              <tr>
              <% @week.reading_lists.each do |reading_list| %>
                <td><%= reading_list.day.strftime("%A, %e %B") %></td>
                <td><%= reading_list.verse %></td>
                <td><%= reading_list.title %></td>  
                <td><%= link_to 'Edit' %> | <%= link_to 'Delete', reading_list_path(reading_list), method: :delete,
               data: { confirm: 'Are you sure?' } %></td>
              </tr>
              <% end %>
            </table>
          </div>
          </div>
          <div class="col-sm-6">
            <div class="container">
              <%= render 'reading_lists/form' %>
            </div>
          </div>
        </div>  
      </div>
    </div>
    <br>
    <div class="row">
      <div class="col-sm-6">
        <div class="card">
          <div class="card-block">
          <br>
            <div class="container">
              <h6>Share</h6>
              <%= render @week.shares %>
            </div>
            <br>
            <div class="container">
              <h6>Add a Question to Share</h6>
              <%= render 'shares/form' %> 
            </div>
          </div>
        <br>
        </div>
      </div>
      <div class="col-sm-6">
        <div class="card">
          <div class="card-block">
          <br>
            <div class="container">
              <h6>Talk</h6>
              <%= render @week.talks %>
            </div>
            <br>
            <div class="container">
              <h6>Add a Question to Talk</h6>
              <%= render 'talks/form' %> 
            </div>
          </div>
          <br>
        </div>
      </div>
    </div>
  <br>
  <div class="row">
    <div class="col-sm-6">
      <div class="card">
        <div class="card-block">
        <br>
          <div class="container">
            <h6>Prayer</h6>
            <%= render @week.prays %>
          </div>
          <br>
          <div class="container">
            <h6>Add a Prayer</h6>
            <%= render 'prays/form' %> 
          </div>
        </div>
        <br>
      </div>
    </div>
    <div class="col-sm-6">
      <div class="card">
        <div class="card-block">
        <br>
          <div class="container">
            <h6>Blessing</h6>
            <%= render @week.blesses %>
          </div>
          <br>
          <div class="container">
            <h6>Add a Blessing</h6>
            <%= render 'blesses/form' %> 
          </div>
        </div>
        <br>
      </div>
    </div>
  </div>
  <br>



    <div class="card">
      <div class="card-block">
        <!--<div class="card-header">
          <div class="card-title">  
            Memory Verse for <%= @week.name %></div>
        </div>-->
        <br>
        <div class="row">
          <div class="col-sm-6">
            <div class="container">
              <h6>Memory Verse</h6>
              <%= render @week.memory_verses %>
            </div>
          </div>
        <div class="col-sm-6">
           <div class="container">
             <h6>Add a Memory Verse</h6>
             <%= render 'memory_verses/form' %> 
           </div>
         </div>
        </div>
        <br>
     </div>
   </div>
  <br>
  <div class="card">
    <div class="card-block">
      <!--<div class="card-header">
        <div class="card-title">  
          Creative Response for <%= @week.name %></div>
      </div>-->
      <br> 
      <div class="row">
        <div class="col-sm-6"> 
          <div class="container">
            <h6>Creative Response</h6>
            <%= render @week.creative_responses %>
          </div>
        </div>
        <div class="col-sm-6">
          <div class="container">
            <h6>Add a Creative Response</h6>
            <%= render 'creative_responses/form' %>
          </div>
        </div>
      </div>
      <br>
    </div>
  </div>
  <br>
  <div class="card">
    <div class="card-block">
      <!--<div class="card-header">
        <div class="card-title">  
          Mealtime Prayer for <%= @week.name %></div>
      </div>-->
      <br> 
      <div class="row">
        <div class="col-sm-6">
          <div class="container">
            <h6>Mealtime Prayer</h6>
            <%= render @week.mealtime_prayers %>
          </div>
        </div>
        <div class="col-sm-6">
          <div class="container">
            <h6>Add a Mealtime Prayer</h6>
            <%= render 'mealtime_prayers/form' %>
          </div>
        </div>
      </div>
      <br>
    </div>
  </div>
  <br>
  <div class="card">
    <div class="card-block">
      <!--<div class="card-header">
        <div class="card-title">  
          Service Idea for <%= @week.name %></div>
      </div>-->
      <br>
      <div class="row">
        <div class="col-sm-6">
          <div class="container">
            <h6>Service Idea</h6>
            <%= render @week.service_ideas %>
          </div>
        </div>
        <div class="col-sm-6">
          <div class="container">
            <h6>Add a Service Idea</h6>
            <%= render 'service_ideas/form' %>
          </div>
        </div>
      </div>
      <br>
    </div>
  </div>
  
</div>
<br>
<% if @week.completed == false %>
<div class="button">
<%= button_to 'Mark Complete',  mark_complete_week_path(@week), class: "btn btn-success" %>
</div>
<% end %>
<br>

app/views/weeks/manage_weeks_current.html.erb
<div class="container-fluid">
  <%= link_to 'Back to Current Week', current_week_weeks_path %>
  <br>
  <br>
  <div class="container-fluid">
    <h2><%= @week.name %></h2>
    <p>This week is currently stored in Current Weeks.</p>
  </div>
  <div class="container-fluid">
    <div class="card">
      <div class="card-block">
        <div class="row">
          <div class="col-sm-12">
            <div class="container">Church Season: <%= @week.season.church_season %></div>
            <div class="container">Publish Date: <%= @week.published_on.strftime("%A, %e %B, %Y")  %></div>
            <div class="container">Archive Date: <%= @week.archived_on.strftime("%A, %e %B, %Y")  %></div>
            <div class="container"><%= link_to 'Edit', edit_week_path(@week) %></div>
          </div>
        </div>
      </div>
    </div>
    <br>
      <div class="card">
        <div class="card-block">
          <br>
          <div class="row">
          <div class="col-sm-6">
            <div class="container">
            <table class="table table-striped table-responsive">
              <thead>Reading List</thead>
              <tr>
                <th>Date</th>
                <th>Verse</th>
                <th>Title</th>
                <th></th>
              </tr>
              <tr>
              <% @week.reading_lists.each do |reading_list| %>
                <td><%= reading_list.day.strftime("%A, %e %B") %></td>
                <td><%= reading_list.verse %></td>
                <td><%= reading_list.title %></td>  
                <td><%= link_to 'Edit' %> | <%= link_to 'Delete', reading_list_path(reading_list), method: :delete,
               data: { confirm: 'Are you sure?' } %></td>
              </tr>
              <% end %>
            </table>
          </div>
          </div>
          <div class="col-sm-6">
            <div class="container">
              <%= render 'reading_lists/form' %>
            </div>
          </div>
        </div>  
      </div>
    </div>
    <br>
    <div class="row">
      <div class="col-sm-6">
        <div class="card">
          <div class="card-block">
          <br>
            <div class="container">
              <h6>Share</h6>
              <%= render @week.shares %>
            </div>
            <br>
            <div class="container">
              <h6>Add a Question to Share</h6>
              <%= render 'shares/form' %> 
            </div>
          </div>
        <br>
        </div>
      </div>
      <div class="col-sm-6">
        <div class="card">
          <div class="card-block">
          <br>
            <div class="container">
              <h6>Talk</h6>
              <%= render @week.talks %>
            </div>
            <br>
            <div class="container">
              <h6>Add a Question to Talk</h6>
              <%= render 'talks/form' %> 
            </div>
          </div>
          <br>
        </div>
      </div>
    </div>
  <br>
  <div class="row">
    <div class="col-sm-6">
      <div class="card">
        <div class="card-block">
        <br>
          <div class="container">
            <h6>Prayer</h6>
            <%= render @week.prays %>
          </div>
          <br>
          <div class="container">
            <h6>Add a Prayer</h6>
            <%= render 'prays/form' %> 
          </div>
        </div>
        <br>
      </div>
    </div>
    <div class="col-sm-6">
      <div class="card">
        <div class="card-block">
        <br>
          <div class="container">
            <h6>Blessing</h6>
            <%= render @week.blesses %>
          </div>
          <br>
          <div class="container">
            <h6>Add a Blessing</h6>
            <%= render 'blesses/form' %> 
          </div>
        </div>
        <br>
      </div>
    </div>
  </div>
  <br>



    <div class="card">
      <div class="card-block">
        <!--<div class="card-header">
          <div class="card-title">  
            Memory Verse for <%= @week.name %></div>
        </div>-->
        <br>
        <div class="row">
          <div class="col-sm-6">
            <div class="container">
              <h6>Memory Verse</h6>
              <%= render @week.memory_verses %>
            </div>
          </div>
        <div class="col-sm-6">
           <div class="container">
             <h6>Add a Memory Verse</h6>
             <%= render 'memory_verses/form' %> 
           </div>
         </div>
        </div>
        <br>
     </div>
   </div>
  <br>
  <div class="card">
    <div class="card-block">
      <!--<div class="card-header">
        <div class="card-title">  
          Creative Response for <%= @week.name %></div>
      </div>-->
      <br> 
      <div class="row">
        <div class="col-sm-6"> 
          <div class="container">
            <h6>Creative Response</h6>
            <%= render @week.creative_responses %>
          </div>
        </div>
        <div class="col-sm-6">
          <div class="container">
            <h6>Add a Creative Response</h6>
            <%= render 'creative_responses/form' %>
          </div>
        </div>
      </div>
      <br>
    </div>
  </div>
  <br>
  <div class="card">
    <div class="card-block">
      <!--<div class="card-header">
        <div class="card-title">  
          Mealtime Prayer for <%= @week.name %></div>
      </div>-->
      <br> 
      <div class="row">
        <div class="col-sm-6">
          <div class="container">
            <h6>Mealtime Prayer</h6>
            <%= render @week.mealtime_prayers %>
          </div>
        </div>
        <div class="col-sm-6">
          <div class="container">
            <h6>Add a Mealtime Prayer</h6>
            <%= render 'mealtime_prayers/form' %>
          </div>
        </div>
      </div>
      <br>
    </div>
  </div>
  <br>
  <div class="card">
    <div class="card-block">
      <!--<div class="card-header">
        <div class="card-title">  
          Service Idea for <%= @week.name %></div>
      </div>-->
      <br>
      <div class="row">
        <div class="col-sm-6">
          <div class="container">
            <h6>Service Idea</h6>
            <%= render @week.service_ideas %>
          </div>
        </div>
        <div class="col-sm-6">
          <div class="container">
            <h6>Add a Service Idea</h6>
            <%= render 'service_ideas/form' %>
          </div>
        </div>
      </div>
      <br>
    </div>
  </div>
  
</div>
<br>
<% if @week.completed == false %>
<div class="button">
<%= button_to 'Mark Complete',  mark_complete_week_path(@week), class: "btn btn-success" %>
</div>
<% end %>
<br>

app/views/weeks/manage_weeks_queue.html.erb
<div class="container-fluid">
  <%= link_to 'Back to Queued Weeks', queue_weeks_path %>
  <br>
  <br>
  <div class="container-fluid">
    <h2><%= @week.name %></h2>
    <p>This week is currently stored in Queued Weeks.</p>
  </div> 
  <div class="container-fluid">
    <div class="card">
      <div class="card-block">
        <div class="row">
          <div class="col-sm-12">
            <div class="container">Church Season: <%= @week.season.church_season %></div>
            <div class="container">Publish Date: <%= @week.published_on.strftime("%A, %e %B, %Y")  %></div>
            <div class="container">Archive Date: <%= @week.archived_on.strftime("%A, %e %B, %Y")  %></div>
            <div class="container"><%= link_to 'Edit', edit_week_path(@week) %></div>
          </div>
        </div>
      </div>
    </div>
    <br>
      <div class="card">
        <div class="card-block">
          <br>
          <div class="row">
          <div class="col-sm-6">
            <div class="container">
            <table class="table table-striped table-responsive">
              <thead>Reading List</thead>
              <tr>
                <th>Date</th>
                <th>Verse</th>
                <th>Title</th>
                <th></th>
              </tr>
              <tr>
              <% @week.reading_lists.each do |reading_list| %>
                <td><%= reading_list.day.strftime("%A, %e %B") %></td>
                <td><%= reading_list.verse %></td>
                <td><%= reading_list.title %></td>  
                <td><%= link_to 'Edit' %> | <%= link_to 'Delete', reading_list_path(reading_list), method: :delete,
               data: { confirm: 'Are you sure?' } %></td>
              </tr>
              <% end %>
            </table>
          </div>
          </div>
          <div class="col-sm-6">
            <div class="container">
              <%= render 'reading_lists/form' %>
            </div>
          </div>
        </div>  
      </div>
    </div>
    <br>
    <div class="row">
      <div class="col-sm-6">
        <div class="card">
          <div class="card-block">
          <br>
            <div class="container">
              <h6>Share</h6>
              <%= render @week.shares %>
            </div>
            <br>
            <div class="container">
              <h6>Add a Question to Share</h6>
              <%= render 'shares/form' %> 
            </div>
          </div>
        <br>
        </div>
      </div>
      <div class="col-sm-6">
        <div class="card">
          <div class="card-block">
          <br>
            <div class="container">
              <h6>Talk</h6>
              <%= render @week.talks %>
            </div>
            <br>
            <div class="container">
              <h6>Add a Question to Talk</h6>
              <%= render 'talks/form' %> 
            </div>
          </div>
          <br>
        </div>
      </div>
    </div>
  <br>
  <div class="row">
    <div class="col-sm-6">
      <div class="card">
        <div class="card-block">
        <br>
          <div class="container">
            <h6>Prayer</h6>
            <%= render @week.prays %>
          </div>
          <br>
          <div class="container">
            <h6>Add a Prayer</h6>
            <%= render 'prays/form' %> 
          </div>
        </div>
        <br>
      </div>
    </div>
    <div class="col-sm-6">
      <div class="card">
        <div class="card-block">
        <br>
          <div class="container">
            <h6>Blessing</h6>
            <%= render @week.blesses %>
          </div>
          <br>
          <div class="container">
            <h6>Add a Blessing</h6>
            <%= render 'blesses/form' %> 
          </div>
        </div>
        <br>
      </div>
    </div>
  </div>
  <br>



    <div class="card">
      <div class="card-block">
        <!--<div class="card-header">
          <div class="card-title">  
            Memory Verse for <%= @week.name %></div>
        </div>-->
        <br>
        <div class="row">
          <div class="col-sm-6">
            <div class="container">
              <h6>Memory Verse</h6>
              <%= render @week.memory_verses %>
            </div>
          </div>
        <div class="col-sm-6">
           <div class="container">
             <h6>Add a Memory Verse</h6>
             <%= render 'memory_verses/form' %> 
           </div>
         </div>
        </div>
        <br>
     </div>
   </div>
  <br>
  <div class="card">
    <div class="card-block">
      <!--<div class="card-header">
        <div class="card-title">  
          Creative Response for <%= @week.name %></div>
      </div>-->
      <br> 
      <div class="row">
        <div class="col-sm-6"> 
          <div class="container">
            <h6>Creative Response</h6>
            <%= render @week.creative_responses %>
          </div>
        </div>
        <div class="col-sm-6">
          <div class="container">
            <h6>Add a Creative Response</h6>
            <%= render 'creative_responses/form' %>
          </div>
        </div>
      </div>
      <br>
    </div>
  </div>
  <br>
  <div class="card">
    <div class="card-block">
      <!--<div class="card-header">
        <div class="card-title">  
          Mealtime Prayer for <%= @week.name %></div>
      </div>-->
      <br> 
      <div class="row">
        <div class="col-sm-6">
          <div class="container">
            <h6>Mealtime Prayer</h6>
            <%= render @week.mealtime_prayers %>
          </div>
        </div>
        <div class="col-sm-6">
          <div class="container">
            <h6>Add a Mealtime Prayer</h6>
            <%= render 'mealtime_prayers/form' %>
          </div>
        </div>
      </div>
      <br>
    </div>
  </div>
  <br>
  <div class="card">
    <div class="card-block">
      <!--<div class="card-header">
        <div class="card-title">  
          Service Idea for <%= @week.name %></div>
      </div>-->
      <br>
      <div class="row">
        <div class="col-sm-6">
          <div class="container">
            <h6>Service Idea</h6>
            <%= render @week.service_ideas %>
          </div>
        </div>
        <div class="col-sm-6">
          <div class="container">
            <h6>Add a Service Idea</h6>
            <%= render 'service_ideas/form' %>
          </div>
        </div>
      </div>
      <br>
    </div>
  </div>
  
</div>
<br>
<% if @week.completed == false %>
<div class="button">
<%= button_to 'Mark Complete',  mark_complete_week_path(@week), class: "btn btn-success" %>
</div>
<% end %>
<br>

app/views/weeks/new.html.erb
<div class="new-weeks-container">
  <div class="d-flex justify-content-center">
    <h1>New Weeks</h1>
  </div>
  <br>
  <hr>
  <div class="d-flex justify-content-center">
      <%= render 'form' %>
  </div>
  <br>
  <hr>
  <div class="d-flex justify-content-center">
    <div class="container" style="width: 50%; text-align: center;">
    <p>These weeks have not been added to the queue. To move the new weeks into the queue, finish adding content by going to "Manage Week" and then press "Add to Queue".</p>
    </div>
  </div>
  <div class="container-fluid" style="width: 75%;" >
    <table class="table table-striped table-responsive" style="background-color: white;">
      <tr>
        <th>Week Name</th>
        <th>Publishing Dates</th>
        <th>Season</th>
        <th>Week Complete?</th>
        <th></th>
        <th></th>
        <!--<th></th>-->
        <th></th>
      </tr>
      <% @weeks.each do |week| %>
      <tr>
	      <td><%= week.name %></td>
        <td><%= week.published_on.strftime("%e %B") %> - <%= week.archived_on.strftime("%e %B, %Y") %></td>
        <td><%= week.season.church_season %></td>
        <td> <% if week.completed == true %>
                  <i class="fa fa-check fa-lg" aria-hidden="true"></i> 
              <% else %>
                  <i class="fa fa-times fa-lg" aria-hidden="true"></i>
              <% end %>
        </td>
	      <td><%= link_to 'Manage Week', week_path(week) %></td>
        <td><%= link_to 'User View', mobile_view_week_path(week), target: "_blank" %></td>
	      <!--<td><%= link_to 'Delete', week_path(week), method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
        <td><%= button_to 'Add to Queue', add_to_queue_week_path(week), class: "btn btn-success" %></td>
      </tr>
      <% end %>
    </table>
    <br>
  </div>
</div>