config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: { sessions: "admins/sessions"}
  resources :pages
  root 'weeks#current'
  namespace :api do
    namespace :vi do
      resources :memory_verses
    end
  end
  resources :seasons
  resources :reading_lists
  resources :creative_responses
  resources :memory_verses
  resources :weeks do
    resources :memory_verses
    resources :mealtime_prayers
    resources :creative_responses
    resources :service_ideas
    resources :faith5s
    resources :shares
    resources :talks
    resources :prays
    resources :blesses
    resources :reading_lists do
      :days
    end
    member do
      get :user_view
    end
    member do
      get :mobile_view

    end
    collection do 
      get :current_week
      get :current
    end
    member do
      get :manage_weeks_current
    end
    member do
      post :add_to_queue
    end
    member do
      post :remove_from_queue
    end
    member do
      post :mark_complete
    end
    member do
      post :publish
    end
    collection do
      get :queue
    end
    member do
      get :manage_weeks_queue
    end
    collection do
      get :archives
    end
    member do
      get :manage_weeks_archived
    end
    member do
      get :user_view_archived
      get :user_view_current
      get :user_view_queue
      get :user_view_new
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/bless.rb
class Bless < ApplicationRecord
  belongs_to :week
end

app/models/day.rb
class Day < ApplicationRecord
  belongs_to :reading_list
end

app/models/faith5.rb
class Faith5 < ApplicationRecord
  belongs_to :week
end

app/models/memory_verse.rb
class MemoryVerse < ApplicationRecord
  belongs_to :week
end

app/models/page.rb
class Page < ApplicationRecord
end

app/models/pray.rb
class Pray < ApplicationRecord
  belongs_to :week
end

app/models/reading_list.rb
class ReadingList < ApplicationRecord
  belongs_to :week
  has_many :days
end

app/models/season.rb
class Season < ApplicationRecord
  has_many :weeks
end

app/models/service_idea.rb
class ServiceIdea < ApplicationRecord
  belongs_to :week
end

app/models/share.rb
class Share < ApplicationRecord
  belongs_to :week
end

app/models/talk.rb
class Talk < ApplicationRecord
  belongs_to :week
end

app/models/week.rb
class Week < ApplicationRecord
  has_many :reading_lists 
  has_many :faith5s
  has_many :service_ideas
  has_many :creative_responses
  has_many :mealtime_prayers
  has_many :memory_verses
  has_many :shares
  has_many :talks
  has_many :prays
  has_many :blesses
  belongs_to :season
  scope :current, -> { 
    where("(published_on < ?) AND 
           (archived_on > ?)", 
            Time.now, Time.now)
  }
  scope :archived, -> { where("archived_on <?", Time.now)}
  scope :queue, -> { where("published_on >?", Time.now)}


end

app/controllers/seasons_controller.rb
class SeasonsController < ApplicationController
  def index
    @seasons = Season.all
  end

  def new
  	@season = Season.new
  end

  def edit
    @season = Season.find(params[:id])
  end

  def create
    @season = Season.new(season_params)

    if @season.save
      redirect_to seasons_path
    else
	  render 'new'
	end
  end

  def update
    @season = Season.find(params[:id])
    if @season.update(season_params)
    	redirect_to seasons_path
    else
      render 'edit'
    end
  end

  def destroy
  	@season = Season.find(params[:id])
  	@season.destroy

  	redirect_to seasons_path
  end

  private
    def season_params
    	params.require(:season).permit(:church_season, :description)
    end
end

app/helpers/blesses_helper.rb
module BlessesHelper
end

app/helpers/days_helper.rb
module DaysHelper
end

app/helpers/faith5s_helper.rb
module Faith5sHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/prays_helper.rb
module PraysHelper
end

app/helpers/seasons_helper.rb
module SeasonsHelper
end

app/helpers/shares_helper.rb
module SharesHelper
end

app/helpers/talks_helper.rb
module TalksHelper
end

app/helpers/week_helper.rb
module WeekHelper
end

app/views/seasons/_form.html.erb
<%= form_for @season do |f| %>
 
  <% if @season.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@season.errors.count, "error") %> prohibited
        this season from being saved:
      </h2>
      <ul>
        <% @season.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 <div class="form-inline">
  <div class="form-group">
    <%= f.label :Season %> 
    <%= f.text_field :church_season, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :Description %>
    <%= f.text_area :description, class: "form-control" %>
  </div>
  <div class="action">
    <%= f.submit  class: "btn btn-primary"%>
  </div>
 </div>
<% end %>

app/views/seasons/edit.html.erb
<h1>Edit Season</h1>

<%= render 'form' %>

<%= link_to 'Back', seasons_path %>

app/views/seasons/index.html.erb
<h1>Seasons</h1>

<%= link_to 'New Season', new_season_path %>
<table class="table table-striped table-responsive">
  <tr>
    <th>Season</th>
    <th>Description</th>
    <th></th>
    <th></th>

  </tr>
  <% @seasons.each do |season| %>
  <tr>
    <td><%= season.church_season %></td>
    <td><%= season.description %></td>
    <td><%= link_to 'Edit', edit_season_path(season) %></td>
	<td><%= link_to 'Delete', season_path(season), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
  <% end %>
 </table>

app/views/seasons/new.html.erb
<%= render 'form' %>